#从Excel文件中需要解析的数据配置
excle:
  data:
    #获取多少行数据
    numLine: 5
    #主要指标
    main:
      #文件名（如：000001_${file}.xls）
      file: main_year
      #需要获取的关键指标
      revenue: 营业总收入(元)
      revenueIncrease: 营业总收入同比增长率
      grossProfitMargin: 销售毛利率
      retainedProfits: 净利润(元)
      retainedProfitsIncrease: 净利润同比增长率
    #利润表
    benefit:
      #文件名（如：000001_${file}.xls）
      file: benefit_year
      #需要获取的关键指标
      researchFee: 研发费用(元)
    #资产负债表
    debt:
      #文件名（如：000001_${file}.xls）
      file: debt_year
      #需要获取的关键指标
      receiveable: 应收账款(元)


